import 'package:horsehouse/core/utils/app_string.dart';

Map<String, String> coreAr = {
  AppString.there: 'بك',
  AppString.hello: 'مرحبا',
  AppString.password: "كلمة المرور",
  AppString.email: 'البريد الإلكتروني',
  AppString.signIn: "تسجيل الدخول",
  AppString.notAMemberYet: 'مستخدم جديد؟',
  AppString.signUpNow: "سجل الآن",
  AppString.emailIsNotCorrect: "البريد الإلكتروني غير صحيح",
  AppString.passwordCriteriaInvalid: "كلمة المرور غير صحيحة، الحد الأدنى 8 حروف وارقام",
  AppString.firstName: "الاسم الأول",
  AppString.lastName: "اسم العائلة",
  AppString.passwordCriteria: "كلمة المرور يجب ان تتكون من 8 حروف وارقام.",
  AppString.confirmPassword: "تأكيد كلمة المرور",
  AppString.signUp: "إنشاء حساب",
  AppString.haveAnAccount: "لديك حساب؟",
  AppString.firstNameAcceptLettersOnly: "الإسم الأول يقبل حروف فقط",
  AppString.firstNameMustBeAtLeast2Characters: "يجب أن يتكون الاسم الأول من حرفين على الأقل",
  AppString.secondNameAcceptLettersOnly: "إسم العائلة يقبل حروف فقط",
  AppString.secondNameMustBeAtLeast2Characters: "يجب أن يتكون اسم العائلة من حرفين على الأقل",
  AppString.passwordDoesntMatch: "كلمة المرور غير مطابقة",
  AppString.confirmPasswordEmpty: "برجاء تأكيد كلمة المرور",
  AppString.ok: 'حسنأ',
  AppString.noAccountWithThisEmail: 'لا يوجد حساب بهذا البريد الإلكتروني',
  AppString.checkThePassword: 'تحقق من كلمة المرور',
  AppString.thisEmailIsRegisterBefore: 'تم تسجيل هذا البريد الإلكتروني من قبل',
  AppString.showAll: 'اظهار الكل',
  AppString.logOut: 'تسجيل خروج',
  AppString.changeLocalization: 'تغيير اللغة',
  AppString.addToCart: 'اضف الي العربه',
  AppString.search: 'بحث',
  AppString.cancel: 'الغاء',
  AppString.noResultFound: 'لم يتم العثور على نتائج',
  AppString.submit: 'حفظ',
  AppString.country: 'الدولة',
  AppString.forgetPassword: 'نسيت كلمة المرور؟',


};
